### ISSUE TITLE
Welcome Field Engineers Walker Grimshaw and Jon Christensen!

### ISSUE THREAD

**Issue by ethan92429** [ethan92429/POST#12]
Hi there Walker and Jon. I want to make sure both of you can access these issues! You will need to make a GitHub account and then comment on this issue. For all issues, if we would like your input, I will label the issue with the "field input needed" label. Also feel free to create your own issues when the need arises. Two useful features of comments is that you can mention other GH people using the '@' symbol... it will alert the person you mentioned to the comment. Try it on me in your comments! also, you can use the '#' symbol to reference other issues. There is a bunch more you can do with issues mentioned [here](https://guides.github.com/features/issues/) . Please comment using your new GH accounts :smile:

**Comment by wngrimshaw** [comment]
@ethan92429, I've got my account setup and am looking forward to what we're able to create this semester

**Comment by ethan92429** [comment]
@wngrimshaw, reading you loud and clear! Thanks for commenting Walker, can't wait to work some more with you!
