### ISSUE TITLE
Put some questions on the same screen

### ISSUE THREAD

**Issue by ethan92429** [ethan92429/POST#16]
@drs354 perhaps we should put all of the plant data questions onto one screen so that operators can fill it out more easily and confirm their answer? What are your thoughts? [Here is how you do that in the form](https://opendatakit.org/help/form-design/examples/#grouping_questions)

**Comment by drs354** [comment]
That seems like a good idea, and it shouldn't take too long to implement.

**Comment by ethan92429** [comment]
Cool! :) No need to do it today though! you should be resting!

**Comment by ethan92429** [comment]
We'll test the many questions/ screen v. the one questions / screen option.
