### ISSUE TITLE
Add navigation bar to the pages website

### ISSUE THREAD

**Issue by ethan92429** [ethan92429/POST#4]
The POST pages website should include a simple, elegant navigation bar. See [here](https://getbootstrap.com/examples/navbar/) for an example, and note that using this would require using Bootstrap... #3

**Comment by aravindpalani** [comment]
@ethan92429 navigation bar for POST pages are compiled but permission is denied from your side. Check my work. :)

**Comment by ethan92429** [comment]
@aravindpalani Ha! it was very surprising to see someone respond to my newly created issue! But I don't see any pull requests... where did you put the code?

**Comment by aravindpalani** [comment]
@ethan92429 Sorry bro! I am new to github so I am having some problem in sync my data with github. Can you help me out ?

**Comment by ethan92429** [comment]
@aravindpalani What is the problem? I jus made [this](https://github.com/ethan92429/POST/wiki/Running-GH-Pages-Locally) guide on how to run and edit the POST gh-pages locally. Once you are confident the changes you propose are working, you can submit a pull request to the POST repo and I will review it. Cheers!

**Comment by aravindpalani** [comment]
@ethan92429 sure thanks..!!

**Comment by aravindpalani** [comment]
@ethan92429 I've attached some 2 screenshots kindly have a lot.
1.Permission is denied for sync.
2. navbar for your index page.
![capture](https://cloud.githubusercontent.com/assets/14292215/12445103/65ff5192-bf88-11e5-89dd-9d1acb8c6a01.JPG)
![capture1](https://cloud.githubusercontent.com/assets/14292215/12445112/6c681230-bf88-11e5-8571-bf6b0229a51a.JPG)

**Comment by ethan92429** [comment]
@aravindpalani Looks great! now you should push those changes to a fork you've made of this repo.... Then create a pull request from that Fork as outlined [here](https://help.github.com/articles/using-pull-requests/)

**Comment by ethan92429** [comment]
Done
